version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    container_name: sample_test_sql
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
      - POSTGRES_INITDB_ARGS=--auth-host=md5 --auth-local=md5
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./Docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:Z # :Z pour podman

  app:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    container_name: sample_test_app
    restart: always
    ports:
      - "8000:80" # backend
      - "3000:3000"
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/frontend
      - .env:/var/www/html/.env
    privileged: true
    depends_on:
      - postgresdb

volumes:
  db-volume:
